# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://Murtaza-Husain1.github.io/crypto_price_data/"

git_url = "https://github.com/Murtaza-Husain1/crypto_price_data/tree/master/"

def custom_doc_links(name): return None
